### ISSUE TITLE
If the code is public, then why use a private git repository?

### ISSUE THREAD

**Issue by CrazyPython** [ogdf/ogdf#20] opened 2016-08-01 20:11 UTC

**Comment by schulzch** [comment] 2016-08-02 08:53
Good question. I guess there are many answers:
1. for historic reasons (was a private SVN in the past)
2. because of research cycles (many researchers are reluctant to publish source code for unpublished papers)

**Comment by CrazyPython** [comment] 2016-08-02 14:54
@schulzch 

2. kinda eliminates the "open" part of Open Graph Drawing Framework. it also slows down development. And if they're reluctant to publish it, then they shouldn't push it to OGDF in the first place - they should make a fork and later merge when the paper is published.

**Comment by schulzch** [comment] 2016-08-03 09:41
True. They should have forked a private `research' branch from Github when switching from SVN to Git.
There is no real reason why this would not work.

Another thing that hampers development is the use of GPL for OGDF. They should have chosen LGPL, because GPL is viral and incompatible with [many open source licenses](https://www.gnu.org/licenses/license-list.en.html). For this reason many developers literally hate to be forced to use GPL and thus do not use GPL-based libraries. Applications are a different story. Luckily OGDF [provides exceptions](https://groups.google.com/d/msg/ogdf/DaI-fXW64YI/5nXuUZpAxncJ), but that is a real obstacle.

Graph Drawing is probably the oldest visualization discipline, yet most libraries have issues with license or software quality. If you're fluent in German you may take a look [here](http://www2.informatik.uni-stuttgart.de/cgi-bin/NCSTRL/NCSTRL_view.pl?id=FACH-0208&mod=0&engl=0&inst=FAK) (non-exhaustive evaluation).

**Comment by sbeyer** [comment] 2017-07-23 00:42
This discussion is a non-issue (not meaning "it's not important" but meaning "it's not a bug"), so I'd like to close this issue.

I can luckily refer to @schulzch in every point regarding the original question. I also underline his "they should have", but apparently (and IMHO unfortunately) we haven't. A mix of political decisions and "we have what we have now"...

However, no comments on the license topic from my side (except: this won't lead anywhere) ;)

**Closed by sbeyer** 2017-07-23 00:42 UTC
